export const typography = {
  materialThemeSubhead1: {
    family: 'Roboto',
    style: 'Medium',
    size: 16,
    weight: 500,
    lineHeight: 24,
  },
  prcBodySmall: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 12,
    weight: 400,
    lineHeight: 16,
  },
  prcBodyMedium: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 14,
    weight: 400,
    lineHeight: 20,
  },
  prcBodyLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 16,
    weight: 400,
    lineHeight: 24,
  },
  prcLabelSmall: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 12,
    weight: 400,
    lineHeight: 16,
  },
  prcLabelMedium: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 14,
    weight: 400,
    lineHeight: 20,
  },
  prcLabelLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 16,
    weight: 400,
    lineHeight: 24,
  },
  prcLabelXtraLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 18,
    weight: 400,
    lineHeight: 25,
  },
  prcTitleSmall: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 18,
    weight: 400,
    lineHeight: 24,
  },
  prcTitleMedium: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 20,
    weight: 400,
    lineHeight: 26,
  },
  prcTitleLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 22,
    weight: 400,
    lineHeight: 28,
  },
  prcHeadlineLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 30,
    weight: 400,
    lineHeight: 38,
  },
  prcHeadlineSmall: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 24,
    weight: 400,
    lineHeight: 32,
  },
  prcHeadlineMedium: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 28,
    weight: 400,
    lineHeight: 36,
  },
  prcHeadlineXtraLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 32,
    weight: 400,
    lineHeight: 40,
  },
  prcHeadlineDoubleXtraLarge: {
    family: 'Qihei Lenovo',
    style: '60S',
    size: 40,
    weight: 400,
    lineHeight: 48,
  },
  rowLabelSmall: {
    family: 'Rookery New',
    style: 'Regular',
    size: 12,
    weight: 400,
    lineHeight: 16,
  },
  rowLabelMedium: {
    family: 'Rookery New',
    style: 'Regular',
    size: 14,
    weight: 400,
    lineHeight: 20,
  },
  rowLabelLarge: {
    family: 'Rookery New',
    style: 'Regular',
    size: 16,
    weight: 400,
    lineHeight: 22,
  },
  rowLabelXtraLarge: {
    family: 'Rookery New',
    style: 'Regular',
    size: 18,
    weight: 400,
    lineHeight: 25,
    letterSpacing: 0.1,
  },
  rowBodySmall: {
    family: 'Rookery New',
    style: 'Regular',
    size: 12,
    weight: 400,
    lineHeight: 16,
  },
  rowBodyMedium: {
    family: 'Rookery New',
    style: 'Regular',
    size: 14,
    weight: 400,
    lineHeight: 20,
  },
  rowBodyLarge: {
    family: 'Rookery New',
    style: 'Regular',
    size: 16,
    weight: 400,
    lineHeight: 24,
  },
  rowTitleSmall: {
    family: 'Rookery New',
    style: 'Regular',
    size: 18,
    weight: 400,
    lineHeight: 24,
  },
  rowTitleSmallBold: {
    family: 'Rookery New',
    style: 'Bold',
    size: 18,
    weight: 700,
    lineHeight: 24,
  },
  rowTitleMediumBold: {
    family: 'Rookery New',
    style: 'Bold',
    size: 20,
    weight: 700,
    lineHeight: 26,
  },
  rowTitleMedium: {
    family: 'Rookery New',
    style: 'Regular',
    size: 20,
    weight: 400,
    lineHeight: 26,
  },
  rowTitleLarge: {
    family: 'Rookery New',
    style: 'Regular',
    size: 22,
    weight: 400,
    lineHeight: 28,
  },
  rowHeadlineSmall: {
    family: 'Rookery New',
    style: 'Bold',
    size: 24,
    weight: 700,
    lineHeight: 32,
  },
  rowHeadlineMedium: {
    family: 'Rookery New',
    style: 'Bold',
    size: 28,
    weight: 700,
    lineHeight: 36,
  },
  rowHeadlineLarge: {
    family: 'Rookery New',
    style: 'Regular',
    size: 30,
    weight: 400,
    lineHeight: 38,
  },
  rowHeadlineXtraLarge: {
    family: 'Rookery New',
    style: 'Bold',
    size: 32,
    weight: 700,
    lineHeight: 40,
  },
  rowHeadlineDoubleXtraLarge: {
    family: 'Rookery New',
    style: 'Bold',
    size: 40,
    weight: 700,
    lineHeight: 48,
  },
} as const;


